name: ci

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12, 14]
                target: [lint, test, stress, disruptor, multi, remote, coverage]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2.1.0
              with:
                node-version: ${{ matrix.node-version }}

            - name: Setup SSH
              run: |
                sudo apt install socat
                ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''
                cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
                ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
                sudo chown $USER:$USER ~/ -R
                sudo chmod o-rwx ~/ -R
                ls -al $HOME/.ssh
                ssh -vvv localhost node --version

            - name: Install
              run: npm ci

            - name: Run tests
              run: npm run ci-${{ matrix.target }}

            - name: Coveralls
              if: matrix.target == 'coverage'
              uses: coverallsapp/github-action@v1.1.1
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
